'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type Project={id:string;name:string;githubOwner:string;githubRepo:string;authorisedStatus:boolean};
export default function NewTaskPage(){
 const router=useRouter(); const [projects,setProjects]=useState<Project[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const [form,setForm]=useState({projectId:'',title:'',completeInstruction:'',riskLevel:'medium'});
 useEffect(()=>{fetch('/api/projects').then(r=>r.json()).then(d=>{const available=(d as Project[]).filter(p=>p.authorisedStatus);setProjects(available);if(available[0])setForm(f=>({...f,projectId:available[0].id}));});},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(r.ok)router.push(`/tasks/${d.id}`);else{setError(d.error||'Unable to create task');setBusy(false);}}
 return <div className="page-stack narrow"><header className="page-header"><div><p className="eyebrow">NEW WORK ITEM</p><h1>Create a task</h1><p>Describe the outcome completely. The agent will produce a plan before any code runs.</p></div></header><form className="panel form" onSubmit={submit}>{error&&<div className="notice error">{error}</div>}<label>Boosta workspace<select value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value})} required><option value="">Select a workspace</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.githubOwner}/{p.githubRepo}</option>)}</select></label><label>Task title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} minLength={3} maxLength={160} required placeholder="Example: Add Stockholm event filtering"/></label><label>Complete instruction<textarea value={form.completeInstruction} onChange={e=>setForm({...form,completeInstruction:e.target.value})} minLength={20} maxLength={12000} required rows={10} placeholder="Explain the goal, requirements, constraints, and how success should be tested."/></label><label>Risk level<select value={form.riskLevel} onChange={e=>setForm({...form,riskLevel:e.target.value})}><option value="low">Low — contained UI or documentation work</option><option value="medium">Medium — normal application change</option><option value="high">High — auth, infrastructure, data, or deployment</option></select></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>router.back()}>Cancel</button><button disabled={busy||!projects.length} className="button primary">{busy?'Creating…':'Create draft task'}</button></div>{!projects.length&&<p className="muted">Authorize a Boosta workspace before creating work.</p>}</form></div>;
}
