import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getSession, isSameOrigin } from '@/lib/auth';
import { enqueueExecution, enqueuePlan, getRedis } from '@/lib/queue';
import { emitTaskEvent, transitionTask } from '@foundry/state-machine';
import { asDeclaredRisk, classifyTaskRisk, evaluateAutonomy, isAutoApproveRisk } from '@foundry/policy';
import { EMERGENCY_STOP_KEY } from '@foundry/ops';

async function admin(request?:Request){const session=await getSession();if(!session)return{error:NextResponse.json({error:'Unauthorized'},{status:401})};if(session.role!=='ADMIN')return{error:NextResponse.json({error:'Forbidden'},{status:403})};if(request&&!isSameOrigin(request))return{error:NextResponse.json({error:'Invalid origin'},{status:403})};return{session};}
export async function GET(){const auth=await admin();if(auth.error)return auth.error;return NextResponse.json(await prisma.projectRun.findMany({orderBy:{startedAt:'desc'},take:50,include:{project:{select:{name:true,githubOwner:true,githubRepo:true}},_count:{select:{tasks:true}}}}));}
export async function POST(request:Request){const auth=await admin(request);if(auth.error)return auth.error;try{const body=await request.json();if(typeof body.projectId!=='string'||typeof body.objective!=='string'||body.objective.trim().length<80)return NextResponse.json({error:'Project and an objective of at least 80 characters are required.'},{status:400});const project=await prisma.project.findUnique({where:{id:body.projectId},include:{policies:{where:{active:true},orderBy:{version:'desc'},take:1}}});if(!project||!project.authorisedStatus)return NextResponse.json({error:'Project must be authorized.'},{status:409});const policy=project.policies[0];if(!policy?.autonomousMode)return NextResponse.json({error:'Enable autonomous mode in a versioned project policy first.'},{status:409});const active=await prisma.projectRun.findFirst({where:{projectId:project.id,status:'RUNNING'}});if(active)return NextResponse.json({error:'An autonomous run is already active.',projectRunId:active.id},{status:409});const result=await prisma.$transaction(async tx=>{const run=await tx.projectRun.create({data:{projectId:project.id,policyVersion:policy.version,objective:body.objective.trim().slice(0,10000),startedBy:auth.session!.userId}});const task=await tx.task.create({data:{projectId:project.id,projectRunId:run.id,title:`AI Project Manager Evaluation — ${project.name}`,completeInstruction:`Create a bounded implementation plan for this authorized project objective. Produce concrete tasks, dependencies, acceptance criteria, testing, security review, failure evidence, and recommendations. Never merge, deploy production, change authentication/firewall/secrets, delete data, contact third parties, or approve RED/BLACK work. Objective:\n\n${body.objective.trim()}`,riskLevel:'high'}});await emitTaskEvent(tx,{taskId:task.id,type:'task_created',actor:'autonomy-controller',actorType:'system',payload:{projectRunId:run.id}});await transitionTask(tx,{taskId:task.id,to:'PLANNING',actor:'autonomy-controller',actorType:'system',reason:'authorized project run started',legacyStatus:'planning',extraTaskData:{startedAt:new Date()}});await tx.auditEvent.create({data:{actor:auth.session!.userId,action:'project_run.started',target:run.id,result:'success',metadata:{projectId:project.id,policyVersion:policy.version}}});return{run,task};});try{await enqueuePlan(result.task.id);}catch{await prisma.projectRun.update({where:{id:result.run.id},data:{status:'FAILED',finishedAt:new Date(),report:{error:'Planning queue unavailable'}}});return NextResponse.json({error:'Planning queue unavailable; run marked failed.',projectRunId:result.run.id},{status:503});}return NextResponse.json({projectRunId:result.run.id,managerTaskId:result.task.id,status:'RUNNING'},{status:201});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to start project run'},{status:400});}}

export async function PATCH(request:Request){
 const auth=await admin(request);if(auth.error)return auth.error;
 try{
  const body=await request.json();if(body.action!=="approve_execution"||typeof body.runId!=="string")return NextResponse.json({error:"Invalid project-run action."},{status:400});
  const run=await prisma.projectRun.findUnique({where:{id:body.runId},include:{project:{include:{policies:{where:{active:true},orderBy:{version:"desc"},take:1}}},tasks:{where:{state:"AWAITING_APPROVAL"},include:{approvals:{where:{approvalType:"plan",decision:"pending"}}}}}});
  if(!run)return NextResponse.json({error:"Project run not found."},{status:404});
  if(run.status!=="READY_FOR_REVIEW"||run.executionApprovedAt)return NextResponse.json({error:"This project run is not waiting for execution approval."},{status:409});
  const row=run.project.policies[0];if(!run.project.authorisedStatus||!row?.autonomousMode)return NextResponse.json({error:"Project autonomy is no longer authorized."},{status:409});
  if((await getRedis().get(EMERGENCY_STOP_KEY))!==null)return NextResponse.json({error:"Emergency stop is engaged. Nothing was queued."},{status:409});
  const policy={autonomousMode:row.autonomousMode,autoApproveMaxRisk:isAutoApproveRisk(row.autoApproveMaxRisk)?row.autoApproveMaxRisk:"medium" as const,maxParallelTasks:row.maxParallelTasks,maxRepairAttempts:row.maxRepairAttempts,maxTasksPerRun:row.maxTasksPerRun,maxTaskCost:Number(row.maxTaskCost),maxProjectRunCost:Number(row.maxProjectRunCost),createDraftPullRequests:row.createDraftPullRequests};
  const total=await prisma.task.count({where:{projectRunId:run.id}});const report=run.report&&typeof run.report==="object"&&!Array.isArray(run.report)?run.report as {summary?:{estimatedCost?:number}}:null;const runEstimatedCost=Number(report?.summary?.estimatedCost||0);
  const eligible=run.tasks.filter(task=>{if(!task.approvals.length)return false;const risk=classifyTaskRisk({declaredRisk:asDeclaredRisk(task.riskLevel),title:task.title,instruction:task.completeInstruction});return evaluateAutonomy(policy,{projectAuthorized:true,risk:risk.level,taskEstimatedCost:0,runEstimatedCost,tasksInRun:Math.max(0,total-1),activeTasks:0,repairAttempts:0,emergencyStop:false}).decision==="AUTO_APPROVE";});
  if(!eligible.length)return NextResponse.json({error:"No GREEN or YELLOW planned tasks are eligible for bundled execution."},{status:409});
  const now=new Date();await prisma.$transaction(async tx=>{for(const task of eligible){await transitionTask(tx,{taskId:task.id,to:"QUEUED",actor:auth.session!.userId,actorType:"human",reason:"approved in project execution bundle",legacyStatus:"queued",extraTaskData:{assignedAgent:"Agent Foundry Runner"}});await tx.approval.updateMany({where:{taskId:task.id,approvalType:"plan",decision:"pending"},data:{decision:"approved",approvedBy:auth.session!.userId,approvedAt:now,comments:"Approved through the project-level execution bundle."}});await emitTaskEvent(tx,{taskId:task.id,type:"plan_approved",actor:auth.session!.userId,actorType:"human",payload:{gate:"project_bundle",projectRunId:run.id}});}await tx.projectRun.update({where:{id:run.id},data:{status:"RUNNING",executionApprovedAt:now,approvedBy:auth.session!.userId,finishedAt:null}});await tx.auditEvent.create({data:{actor:auth.session!.userId,action:"project_run.execution_approved",target:run.id,result:"success",metadata:{queued:eligible.length,heldForHuman:run.tasks.length-eligible.length}}});});
  const queued:string[]=[];try{for(const task of eligible){const {job,deduplicated}=await enqueueExecution(task.id);queued.push(task.id);await emitTaskEvent(prisma,{taskId:task.id,type:"task_queued",actor:auth.session!.userId,actorType:"human",correlationId:job.id??null,payload:{jobId:job.id??null,deduplicated,source:"project_bundle"}});}}catch{const notQueued=eligible.filter(task=>!queued.includes(task.id));await prisma.$transaction(async tx=>{for(const task of notQueued){await transitionTask(tx,{taskId:task.id,to:"AWAITING_APPROVAL",actor:auth.session!.userId,actorType:"human",reason:"execution queue unavailable; bundled approval rolled back",legacyStatus:"awaiting_plan_approval"});await tx.approval.updateMany({where:{taskId:task.id,approvalType:"plan",decision:"approved"},data:{decision:"pending",approvedBy:null,approvedAt:null}});}await tx.projectRun.update({where:{id:run.id},data:{status:"READY_FOR_REVIEW",executionApprovedAt:null,approvedBy:null,finishedAt:new Date()}});});return NextResponse.json({error:"The execution queue became unavailable. Unqueued tasks were safely returned to review.",queued:queued.length},{status:503});}
  return NextResponse.json({message:`Approved ${eligible.length} planned tasks. Guarded execution has started.`,queued:eligible.length,heldForHuman:run.tasks.length-eligible.length});
 }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to approve project execution"},{status:400});}
}