'use client';
import { useEffect, useState } from 'react';
type Project = { id: string; name: string; authorisedStatus: boolean };
export default function CommandCenter() {
  const [projects, setProjects] = useState<Project[]>([]), [projectId, setProjectId] = useState(''), [command, setCommand] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { fetch('/api/project-autonomy').then(async response => { if (response.ok) { const rows = await response.json(); setProjects(rows); if (rows[0]) setProjectId(rows[0].id); } }); }, []);
  async function submit() { if (!projectId || command.trim().length < 3) return; setBusy(true); setMessage(''); try { const response = await fetch('/api/boosta-command', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId, command }) }); const data = await response.json(); setMessage(response.ok ? `${data.message} Mission: ${data.missionId}` : data.error); if (response.ok) setCommand(''); } finally { setBusy(false); } }
  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">BOOSTA COMMAND CENTER</p><h1>Give Boosta a command</h1><p>Commands become governed mission requests. Boosta will not execute external actions without the required approvals.</p></div></header>{message && <div className="notice">{message}</div>}<section className="panel page-stack"><label>Workspace<select value={projectId} onChange={event => setProjectId(event.target.value)}>{projects.map(project => <option key={project.id} value={project.id}>{project.name}{project.authorisedStatus ? '' : ' (not authorized)'}</option>)}</select></label><label>Command<textarea rows={8} value={command} onChange={event => setCommand(event.target.value)} placeholder="Example: Research three low-cost ways to improve our audiobook sales and prepare a recommendation with sources, risks, and next steps." /></label><div className="action-buttons"><button className="button primary" disabled={busy || !projectId || command.trim().length < 3} onClick={() => void submit()}>Send governed command</button><span>Creates a draft mission for review.</span></div></section></div>;
}
