import prisma from '@/lib/prisma';
import { estimateUsd, parseRatePerMillion, RATE_ENV } from '@foundry/cost';
import { nextTaskAction, redactDashboardText } from './status';
import type { ActivityItem, AttentionItem, CostSnapshot, DashboardCounts, MissionSummary } from './types';

const activeMissionStatuses=['approved','running','active','executing'];
const activeTaskStates=['QUEUED','PLANNING','RUNNING','VALIDATING','REPAIRING','REVIEWING','PR_CREATED','PREVIEW_PENDING','PREVIEW_READY'] as const;
const blockedTaskStates=['AWAITING_APPROVAL','CHANGES_REQUESTED','HUMAN_INPUT_REQUIRED','SECURITY_BLOCKED'] as const;
const failedTaskStates=['FAILED','CODE_FAILED','INFRASTRUCTURE_FAILED'] as const;
const completedTaskStates=['COMPLETED','APPROVED'] as const;
const startOfUtcDay=(now:Date)=>new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));
const startOfUtcMonth=(now:Date)=>new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));
const elapsed=(start:Date,now:Date)=>Math.max(0,Math.floor((now.getTime()-start.getTime())/1000));

export async function loadDatabaseToday(now=new Date()):Promise<{counts:DashboardCounts;cost:CostSnapshot;missions:MissionSummary[];attention:AttentionItem[];activity:ActivityItem[];databaseAvailable:true}>{
 const day=startOfUtcDay(now),month=startOfUtcMonth(now),rate=parseRatePerMillion(process.env[RATE_ENV]);
 const [activeMissions,activeTasks,waitingTasks,blockedTasks,failedTasks,pendingTaskApprovals,pendingMissionApprovals,redApprovals,todayUsage,monthUsage,missions,pendingApprovalRows,problemTasks,taskEvents,missionEvents,audits]=await Promise.all([
  prisma.mission.count({where:{status:{in:activeMissionStatuses}}}),prisma.task.count({where:{state:{in:[...activeTaskStates]}}}),prisma.task.count({where:{state:{in:['QUEUED','PLANNING']}}}),prisma.task.count({where:{state:{in:[...blockedTaskStates]}}}),prisma.task.count({where:{state:{in:[...failedTaskStates]}}}),prisma.approval.count({where:{decision:'pending'}}),prisma.missionApproval.count({where:{decision:'pending'}}),prisma.approval.count({where:{decision:'pending',task:{riskLevel:'high'}}}),
  prisma.agentRun.aggregate({_sum:{tokenUsage:true},where:{createdAt:{gte:day},provider:'google'}}),prisma.agentRun.aggregate({_sum:{tokenUsage:true},where:{createdAt:{gte:month},provider:'google'}}),
  prisma.mission.findMany({where:{status:{in:activeMissionStatuses}},orderBy:{updatedAt:'desc'},take:20,include:{project:{select:{name:true}},approvals:{where:{decision:'pending'},orderBy:{requestedAt:'desc'},take:1},tasks:{orderBy:{sequence:'asc'},include:{task:{select:{id:true,title:true,state:true,assignedAgent:true,startedAt:true,createdAt:true,estimatedCost:true,tokenUsage:true}}}}}}),
  prisma.approval.findMany({where:{decision:'pending'},orderBy:{requestedAt:'asc'},take:30,include:{task:{select:{id:true,title:true,riskLevel:true,projectId:true,missionLink:{select:{missionId:true}}}}}}),
  prisma.task.findMany({where:{state:{in:[...failedTaskStates,'SECURITY_BLOCKED','HUMAN_INPUT_REQUIRED']}},orderBy:{updatedAt:'desc'},take:30,select:{id:true,title:true,state:true,updatedAt:true,projectId:true,missionLink:{select:{missionId:true}}}}),
  prisma.taskEvent.findMany({orderBy:{createdAt:'desc'},take:40,select:{id:true,taskId:true,attemptId:true,type:true,actor:true,actorType:true,correlationId:true,createdAt:true}}),
  prisma.missionEvent.findMany({orderBy:{createdAt:'desc'},take:30,select:{id:true,missionId:true,type:true,actor:true,actorType:true,correlationId:true,createdAt:true}}),
  prisma.auditEvent.findMany({orderBy:{timestamp:'desc'},take:40,select:{id:true,actor:true,action:true,target:true,result:true,timestamp:true}})
 ]);
 const todayTokens=todayUsage._sum.tokenUsage||0,monthTokens=monthUsage._sum.tokenUsage||0;
 const cost:CostSnapshot={spendTodayUsd:estimateUsd(todayTokens,rate),spendMonthUsd:estimateUsd(monthTokens,rate),tokensToday:todayTokens,rateConfigured:rate>0,dailyBudgetUsd:null,dailyBudgetSource:'not_configured'};
 const missionRows:MissionSummary[]=missions.map(mission=>{const tasks=mission.tasks.map(link=>link.task),completed=tasks.filter(task=>completedTaskStates.includes(task.state as typeof completedTaskStates[number])).length,current=tasks.find(task=>activeTaskStates.includes(task.state as typeof activeTaskStates[number])||blockedTaskStates.includes(task.state as typeof blockedTaskStates[number])||failedTaskStates.includes(task.state as typeof failedTaskStates[number]))||null;return{id:mission.id,goal:mission.goal,project:mission.project?.name||null,businessId:mission.businessId,status:mission.status,phase:current?.state||mission.status,progress:{completed,total:tasks.length},activeTask:current?{id:current.id,title:current.title,state:current.state}:null,assignedAgent:current?.assignedAgent||null,elapsedSeconds:elapsed(mission.createdAt,now),budgetUsd:Number(mission.budgetUsd),spendUsd:tasks.reduce((sum,task)=>sum+Number(task.estimatedCost),0),tokens:tasks.reduce((sum,task)=>sum+task.tokenUsage,0),risk:mission.riskLevel,nextAction:current?nextTaskAction(current.state):tasks.length?'No active task.':'Mission has no tasks.',approvalState:mission.approvals[0]?.approvalType||'none'};});
 const attention:AttentionItem[]=[...pendingApprovalRows.map(row=>({id:`approval:${row.id}`,severity:row.task.riskLevel==='high'?'high' as const:'medium' as const,title:`${row.approvalType} approval: ${row.task.title}`,reason:'A human decision is required before work can continue.',ageSeconds:elapsed(row.requestedAt,now),ownerAction:'Review evidence and approve, request changes, or reject.',href:`/tasks/${row.task.id}`,taskId:row.task.id,projectId:row.task.projectId,missionId:row.task.missionLink?.missionId})),...problemTasks.map(task=>({id:`task:${task.id}`,severity:task.state==='SECURITY_BLOCKED'?'critical' as const:task.state==='HUMAN_INPUT_REQUIRED'?'high' as const:'medium' as const,title:`${task.state.replaceAll('_',' ')}: ${task.title}`,reason:nextTaskAction(task.state),ageSeconds:elapsed(task.updatedAt,now),ownerAction:task.state==='SECURITY_BLOCKED'?'Inspect the security evidence; do not resume automatically.':'Inspect the failure evidence and choose a bounded recovery.',href:`/tasks/${task.id}`,taskId:task.id,projectId:task.projectId,missionId:task.missionLink?.missionId}))];
 const activity:ActivityItem[]=[...taskEvents.map(event=>({id:`task:${event.id}`,timestamp:event.createdAt.toISOString(),type:event.type,actor:event.actor,actorType:event.actorType,title:event.type.replaceAll('_',' '),taskId:event.taskId,attemptId:event.attemptId||undefined,correlationId:event.correlationId||undefined})),...missionEvents.map(event=>({id:`mission:${event.id}`,timestamp:event.createdAt.toISOString(),type:event.type,actor:event.actor,actorType:event.actorType,title:event.type.replaceAll('_',' '),missionId:event.missionId,correlationId:event.correlationId||undefined})),...audits.map(event=>({id:`audit:${event.id}`,timestamp:event.timestamp.toISOString(),type:event.action,actor:event.actor,actorType:'audit',title:redactDashboardText(`${event.action} · ${event.result}`),taskId:event.target||undefined}))].sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,40);
 return{databaseAvailable:true,counts:{activeMissions,activeTasks,waitingTasks,blockedTasks,failedTasks,pendingApprovals:pendingTaskApprovals+pendingMissionApprovals,redApprovals},cost,missions:missionRows,attention,activity};
}
