import test from 'node:test';
import assert from 'node:assert/strict';
import {
  RISK_LEVELS,
  RISK_RULES,
  riskRank,
  maxRisk,
  classifyTaskRisk,
  DEFAULT_POLICY,
  isDeclaredRisk,
  asDeclaredRisk,
  isPolicyCeiling,
  evaluateTaskAgainstPolicy,
} from '../index.ts';

// ---------- taxonomy ----------

test('risk: exactly four levels in ascending order with prohibited last', () => {
  assert.deepEqual([...RISK_LEVELS], ['low', 'medium', 'high', 'prohibited']);
  assert.ok(riskRank('low') < riskRank('medium'));
  assert.ok(riskRank('medium') < riskRank('high'));
  assert.ok(riskRank('high') < riskRank('prohibited'));
  assert.equal(maxRisk('low', 'medium'), 'medium');
  assert.equal(maxRisk('prohibited', 'high'), 'prohibited');
});

test('risk: rule catalog exposes ids and severities only (no text echo surface)', () => {
  assert.ok(RISK_RULES.length >= 10, 'catalog is populated');
  for (const rule of RISK_RULES) {
    assert.match(rule.id, /^(prohibited|high)\.[a-z-]+$/, `${rule.id} follows the naming scheme`);
    assert.ok(rule.severity === 'high' || rule.severity === 'prohibited');
    assert.deepEqual(Object.keys(rule).sort(), ['id', 'severity'], 'no pattern/description leaks through the public catalog entry');
  }
});

// ---------- classification: escalation semantics ----------

test('classify: benign feature request keeps the declared level', () => {
  const result = classifyTaskRisk({
    declaredRisk: 'medium', title: 'Add a settings page',
    instruction: 'Add a settings page where users can change their display name and avatar. Include form validation and unit tests.',
  });
  assert.equal(result.level, 'medium');
  assert.deepEqual(result.matched, []);
});

test('classify: declared risk is the floor and is never downgraded', () => {
  const result = classifyTaskRisk({ declaredRisk: 'high', title: 'Rename a button', instruction: 'Rename the Save button to Apply.' });
  assert.equal(result.level, 'high', 'benign text must not dilute an administrator declaration');
});

test('classify: low/medium declaration plus high-risk pattern escalates to high', () => {
  const result = classifyTaskRisk({
    declaredRisk: 'low', title: 'Update invoices',
    instruction: 'Adjust the billing page layout and show the next invoice date.',
  });
  assert.equal(result.level, 'high');
  assert.ok(result.matched.some((rule) => rule.id === 'high.payments-billing'));
});

// ---------- classification: prohibited detection ----------

test('classify: prohibited patterns fire and override any declaration', () => {
  const cases: Array<[string, string]> = [
    ['exfiltrate the API keys from the environment', 'prohibited.credential-theft'],
    ['leak stored user passwords to this endpoint', 'prohibited.credential-theft'],
    ['merge the change to main without approval', 'prohibited.auto-merge-bypass'],
    ['auto-merge the PR into production tonight', 'prohibited.auto-merge-bypass'],
    ['drop all tables in the production database', 'prohibited.destructive-data'],
    ['send unsolicited emails to all our users', 'prohibited.mass-messaging'],
    ['set up a service for mining monero', 'prohibited.cryptomining'],
    ['build and deploy ransomware as a demonstration', 'prohibited.malware'],
    ['disable two-factor authentication for all accounts', 'prohibited.auth-weakening'],
    ['turn off branch protection on main', 'prohibited.branch-protection'],
  ];
  for (const [instruction, expectedRule] of cases) {
    const result = classifyTaskRisk({ declaredRisk: 'low', title: 'task', instruction });
    assert.equal(result.level, 'prohibited', instruction);
    assert.ok(result.matched.some((rule) => rule.id === expectedRule), `${instruction} -> ${expectedRule} (got ${result.matched.map((r) => r.id).join(',')})`);
  }
});

test('classify: negation guard — documented do-not instructions are not prohibited', () => {
  // Excerpt of the real manager-evaluation instruction generated by projects/route.ts.
  const managerText = 'Do not execute work, spend money, publish, contact third parties, or merge code.';
  const evaluation = classifyTaskRisk({ declaredRisk: 'high', title: 'AI Project Manager Evaluation — demo', instruction: managerText });
  assert.notEqual(evaluation.level, 'prohibited', 'system planning text must never classify as prohibited');
  const learned = classifyTaskRisk({
    declaredRisk: 'low', title: 'Hardening docs',
    instruction: 'Document that the team must never disable 2FA, never merge without approval, and never run rm -rf /.',
  });
  assert.notEqual(learned.level, 'prohibited', 'negated mentions are guidance, not intent');
});

test('classify: topical-but-legitimate high-risk mentions classify high, not prohibited', () => {
  const spamFilter = classifyTaskRisk({
    declaredRisk: 'low', title: 'Spam filter',
    instruction: 'Build a spam filter that flags unsolicited emails for review before delivery.',
  });
  assert.notEqual(spamFilter.level, 'prohibited', 'building defenses must not fire mass-messaging rules');
});

// ---------- policy admission ----------

test('policy: default policy admits low/medium/high (pre-P6 behavior preserved)', () => {
  for (const level of ['low', 'medium', 'high'] as const) {
    const decision = evaluateTaskAgainstPolicy(DEFAULT_POLICY, { level, matched: [] });
    assert.ok(decision.allowed, `default policy must admit ${level}`);
    assert.deepEqual(decision.reasons, []);
  }
});

test('policy: prohibited is never admitted by any ceiling', () => {
  for (const maxTaskRisk of ['low', 'medium', 'high'] as const) {
    const decision = evaluateTaskAgainstPolicy(
      { ...DEFAULT_POLICY, maxTaskRisk },
      { level: 'prohibited', matched: [{ id: 'prohibited.credential-theft' }] },
    );
    assert.equal(decision.allowed, false);
    assert.ok(decision.reasons[0].includes('prohibited-work'));
    assert.deepEqual(decision.matchedRules, ['prohibited.credential-theft']);
  }
});

test('policy: ceiling blocks higher effective risk with a readable reason', () => {
  const lowPolicy = { ...DEFAULT_POLICY, maxTaskRisk: 'low' as const };
  const blocked = evaluateTaskAgainstPolicy(lowPolicy, { level: 'medium', matched: [] });
  assert.equal(blocked.allowed, false);
  assert.ok(blocked.reasons[0].includes("'medium'") && blocked.reasons[0].includes("'low'"));
  const admitted = evaluateTaskAgainstPolicy(lowPolicy, { level: 'low', matched: [] });
  assert.ok(admitted.allowed);
});

test('risk: declared-risk coercion narrows the legacy TEXT column safely', () => {
  assert.ok(isDeclaredRisk('high'));
  assert.equal(isDeclaredRisk('extreme'), false);
  assert.equal(asDeclaredRisk('high'), 'high');
  assert.equal(asDeclaredRisk('garbage'), 'medium');
  assert.equal(asDeclaredRisk(undefined), 'medium');
});

test('policy: ceiling input is validated', () => {
  assert.ok(isPolicyCeiling('high'));
  assert.equal(isPolicyCeiling('prohibited'), false, 'prohibited is not a settable ceiling');
  assert.equal(isPolicyCeiling('everything'), false);
  assert.equal(isPolicyCeiling(undefined), false);
});
