import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getSession, isSameOrigin } from '@/lib/auth';
import { parseProjectInput, parsePublicUrl, projectTypes } from '@/lib/validation';
import { enqueuePlan } from '@/lib/queue';
import { transitionTask, emitTaskEvent } from '@foundry/state-machine';

async function requireAdmin(request?: Request) { const session=await getSession();if(!session)return{error:NextResponse.json({error:'Unauthorized'},{status:401})};if(session.role!=='ADMIN')return{error:NextResponse.json({error:'Forbidden'},{status:403})};if(request&&!isSameOrigin(request))return{error:NextResponse.json({error:'Invalid origin'},{status:403})};return{session}; }
export async function GET(){const auth=await requireAdmin();if(auth.error)return auth.error;return NextResponse.json(await prisma.project.findMany({orderBy:{createdAt:'desc'},include:{_count:{select:{tasks:true}}}}));}
export async function POST(request:Request){try{const auth=await requireAdmin(request);if(auth.error)return auth.error;const data=parseProjectInput(await request.json());const existing=await prisma.project.findFirst({where:{githubOwner:{equals:data.githubOwner,mode:'insensitive'},githubRepo:{equals:data.githubRepository,mode:'insensitive'}}});if(existing)return NextResponse.json({error:'This GitHub repository is already registered',projectId:existing.id},{status:409});const project=await prisma.project.create({data:{name:data.name,githubOwner:data.githubOwner,githubRepo:data.githubRepository,defaultBranch:data.defaultBranch,authorisedStatus:false,spendingLimit:data.spendingLimit,projectType:data.projectType,productionUrl:data.productionUrl},include:{_count:{select:{tasks:true}}}});await prisma.auditEvent.create({data:{actor:auth.session!.userId,action:'project.created',target:project.id,result:'success',metadata:{repository:`${project.githubOwner}/${project.githubRepo}`,projectType:project.projectType,productionUrl:project.productionUrl}}});return NextResponse.json(project,{status:201});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Failed to create project'},{status:400});}}
export async function PATCH(request:Request){try{const auth=await requireAdmin(request);if(auth.error)return auth.error;const body=await request.json();if(typeof body.id!=='string')return NextResponse.json({error:'Project id is required'},{status:400});if(body.action==='authorize'||body.action==='deauthorize'){
  const authorisedStatus=body.action==='authorize';
  const project=await prisma.project.update({where:{id:body.id},data:{authorisedStatus},include:{_count:{select:{tasks:true}}}});
  await prisma.auditEvent.create({data:{actor:auth.session!.userId,action:authorisedStatus?'project.authorized':'project.deauthorized',target:project.id,result:'success'}});
  let managerTaskId:string|undefined;
  if(authorisedStatus){
    const active=await prisma.task.findFirst({where:{projectId:project.id,title:{startsWith:'AI Project Manager Evaluation'},status:{in:['draft','planning','awaiting_plan_approval','approved','queued','coding','testing','reviewing','awaiting_human_review','approved_for_merge']}}});
    if(active) managerTaskId=active.id;
    else {
      const instruction=`Act as the AI Project Manager for ${project.name}. Automatically evaluate the repository ${project.githubOwner}/${project.githubRepo}, its current product state, target users, likely market, research needs, branding, marketing, content, operations, inventory or suppliers when relevant, technical architecture, security, privacy, deployment, analytics, budget, timeline, risks, and success measures. Select the specialist personnel needed from the verified agent catalog and produce a phased master plan with dependencies, deliverables, acceptance criteria, owner questions, and explicit approval gates. Where business details are unknown, identify them as questions and do not invent commitments. Do not execute work, spend money, publish, contact third parties, or merge code.`;
      const task=await prisma.$transaction(async tx=>{const created=await tx.task.create({data:{projectId:project.id,title:`AI Project Manager Evaluation — ${project.name}`,completeInstruction:instruction,riskLevel:'high'}});await emitTaskEvent(tx,{taskId:created.id,type:'task_created',actor:'ai-project-manager',actorType:'system',payload:{projectId:project.id,evaluation:true}});await transitionTask(tx,{taskId:created.id,to:'PLANNING',actor:'ai-project-manager',actorType:'system',reason:'manager evaluation queued',legacyStatus:'planning',extraTaskData:{startedAt:new Date()}});return created;});managerTaskId=task.id;
      try{const job=await enqueuePlan(task.id);await prisma.auditEvent.create({data:{actor:'ai-project-manager',action:'project.manager_evaluation_queued',target:project.id,result:'success',metadata:{taskId:task.id,jobId:job.id}}});}
      catch{await transitionTask(prisma,{taskId:task.id,to:'FAILED',actor:'ai-project-manager',actorType:'system',reason:'planning queue unavailable',legacyStatus:'failed'});await prisma.auditEvent.create({data:{actor:'ai-project-manager',action:'project.manager_evaluation_queued',target:project.id,result:'failed',metadata:{taskId:task.id}}});}
    }
  }
  return NextResponse.json({...project,managerTaskId});
}if(body.action==='update_public_link'){const projectType=typeof body.projectType==='string'?body.projectType:'web_app';if(!projectTypes.has(projectType))throw new Error('Invalid project type');const productionUrl=parsePublicUrl(body.productionUrl);const project=await prisma.project.update({where:{id:body.id},data:{projectType,productionUrl},include:{_count:{select:{tasks:true}}}});await prisma.auditEvent.create({data:{actor:auth.session!.userId,action:'project.public_link_updated',target:project.id,result:'success',metadata:{projectType,productionUrl}}});return NextResponse.json(project);}return NextResponse.json({error:'Invalid project action'},{status:400});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Project update failed'},{status:400});}}
export async function DELETE(request:Request){const auth=await requireAdmin(request);if(auth.error)return auth.error;const body=await request.json();if(typeof body.id!=='string'||typeof body.confirmation!=='string')return NextResponse.json({error:'Project id and confirmation are required'},{status:400});const project=await prisma.project.findUnique({where:{id:body.id},include:{_count:{select:{tasks:true}}}});if(!project)return NextResponse.json({error:'Project not found'},{status:404});const expected=`${project.githubOwner}/${project.githubRepo}`;if(body.confirmation!==expected)return NextResponse.json({error:`Type ${expected} exactly to confirm deletion`},{status:400});await prisma.$transaction([prisma.auditEvent.create({data:{actor:auth.session!.userId,action:'project.deleted',target:project.id,result:'success',metadata:{repository:expected,deletedTasks:project._count.tasks}}}),prisma.project.delete({where:{id:project.id}})]);return NextResponse.json({success:true,deletedProject:expected,deletedTasks:project._count.tasks});}
