export const CHARTER_STATUSES=['draft','active','superseded','retired'] as const;
export const MISSION_TYPES=['research_validation','web_design_build','content_engine','micro_saas','business_development','upgrade_maintenance','infrastructure'] as const;
export const PRICING_MODELS=['fixed','hourly','mrr','affiliate','experimental','internal'] as const;
export const CONSEQUENTIAL_APPROVALS=['customer_commitment','public_representation','financial_action','production_deployment','legal_commitment'] as const;
const currencies=new Set(['USD','EUR','GBP','SEK','NOK','DKK','CAD','AUD']);
const list=(value:unknown,name:string,errors:string[],required=true)=>{if(!Array.isArray(value)||(required&&!value.length))errors.push(name+' must be '+(required?'a non-empty':'an')+' array');else if(value.some(item=>typeof item!=='string'||!item.trim()))errors.push(name+' contains an invalid value');};
const int=(value:unknown,name:string,errors:string[],minimum=0)=>{if(typeof value!=='number'||!Number.isSafeInteger(value)||value<minimum)errors.push(name+' must be a safe integer >= '+minimum);};
export interface CharterInput{name:string;goal:string;constraints:string[];allowedToolClasses:string[];requiredApprovalRules:string[];maxMissionBudgetMinor:number;monthlyOperatingBudgetMinor:number;monthlyExperimentBudgetMinor:number;currency:string;defaultTokenBudget:number;hardTokenCeiling:number;maxParallelMissions:number;reviewIntervalDays:number}
export function validateCharter(value:CharterInput):string[]{const e:string[]=[];if(!value.name?.trim())e.push('name is required');if(!value.goal?.trim())e.push('goal is required');list(value.constraints,'constraints',e);list(value.allowedToolClasses,'allowedToolClasses',e);list(value.requiredApprovalRules,'requiredApprovalRules',e);for(const rule of CONSEQUENTIAL_APPROVALS)if(!value.requiredApprovalRules?.includes(rule))e.push('requiredApprovalRules must include '+rule);int(value.maxMissionBudgetMinor,'maxMissionBudgetMinor',e);int(value.monthlyOperatingBudgetMinor,'monthlyOperatingBudgetMinor',e);int(value.monthlyExperimentBudgetMinor,'monthlyExperimentBudgetMinor',e);if(!currencies.has(value.currency))e.push('currency is unsupported');int(value.defaultTokenBudget,'defaultTokenBudget',e,1);int(value.hardTokenCeiling,'hardTokenCeiling',e,1);if(value.hardTokenCeiling<value.defaultTokenBudget)e.push('hardTokenCeiling must be >= defaultTokenBudget');int(value.maxParallelMissions,'maxParallelMissions',e,1);int(value.reviewIntervalDays,'reviewIntervalDays',e,1);return e;}
export interface TemplateInput{key:string;name:string;description:string;missionType:string;defaultRiskLevel:string;defaultBudgetMinor:number;defaultTokenBudget:number;defaultMaxParallelTasks:number;allowedToolClasses:string[];requiredApprovalRules:string[];definitionOfDoneTemplate:string[];failureConditionsTemplate:string[];measurementWindowDays:number;leadingIndicators:string[];laggingIndicators:string[];killCriteria:string[];pricingModels:string[]}
export function validateMissionTemplate(v:TemplateInput):string[]{const e:string[]=[];if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v.key))e.push('invalid template key');if(!v.name?.trim()||!v.description?.trim())e.push('name and description are required');if(!(MISSION_TYPES as readonly string[]).includes(v.missionType))e.push('invalid missionType');if(!['low','medium','high'].includes(v.defaultRiskLevel))e.push('invalid defaultRiskLevel');int(v.defaultBudgetMinor,'defaultBudgetMinor',e);int(v.defaultTokenBudget,'defaultTokenBudget',e,1);int(v.defaultMaxParallelTasks,'defaultMaxParallelTasks',e,1);int(v.measurementWindowDays,'measurementWindowDays',e,1);for(const [n,x] of Object.entries({allowedToolClasses:v.allowedToolClasses,requiredApprovalRules:v.requiredApprovalRules,definitionOfDoneTemplate:v.definitionOfDoneTemplate,failureConditionsTemplate:v.failureConditionsTemplate,leadingIndicators:v.leadingIndicators,laggingIndicators:v.laggingIndicators,killCriteria:v.killCriteria,pricingModels:v.pricingModels}))list(x,n,e);if(v.pricingModels?.some(x=>!(PRICING_MODELS as readonly string[]).includes(x)))e.push('invalid pricing model');return e;}
export function charterCeiling(charter:{maxMissionBudgetMinor:bigint;hardTokenCeiling:number;maxParallelMissions:number;allowedToolClasses:string[];requiredApprovalRules:string[]}){return{maxBudgetUsd:Number(charter.maxMissionBudgetMinor)/100,maxTokenBudget:charter.hardTokenCeiling,maxParallelTasks:charter.maxParallelMissions,allowedToolClasses:charter.allowedToolClasses,requiredApprovalRules:charter.requiredApprovalRules,maxRisk:'high' as const};}
