ALTER TABLE "TwinScenarioResult" ALTER COLUMN "missingData" SET DEFAULT ARRAY[]::TEXT[], ALTER COLUMN "missingData" SET NOT NULL;
ALTER TABLE "HealthSnapshot" ALTER COLUMN "missingData" SET DEFAULT ARRAY[]::TEXT[], ALTER COLUMN "missingData" SET NOT NULL;
ALTER TABLE "HealthSnapshot" ALTER COLUMN "evidenceRefs" SET DEFAULT ARRAY[]::TEXT[], ALTER COLUMN "evidenceRefs" SET NOT NULL;
ALTER TABLE "AttentionItem" ALTER COLUMN "sourceRefs" SET DEFAULT ARRAY[]::TEXT[], ALTER COLUMN "sourceRefs" SET NOT NULL;
