'use client';
import { FormEvent, useState } from 'react';
type Contact = { id: string; name: string };
export function CrmControls({ contacts }: { contacts: Contact[] }) {
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>, action: string) { event.preventDefault(); setBusy(true); setMessage(''); const form = new FormData(event.currentTarget); const response = await fetch('/api/crm', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action, ...Object.fromEntries(form) }) }); const data = await response.json(); setBusy(false); if (!response.ok) { setMessage(data.error ?? 'Request failed'); return; } setMessage('Saved. Reloading…'); window.location.reload(); }
  return <section className="grid-two"><form className="panel form" onSubmit={(event) => submit(event, 'create_contact')}><div className="panel-head"><div><h2>Add contact</h2><p>Human-entered, confidential by default.</p></div></div><label>First name<input name="firstName" required maxLength={120} /></label><label>Last name<input name="lastName" required maxLength={120} /></label><label>Email <input name="email" type="email" maxLength={320} /></label><label>Role or title<input name="title" maxLength={200} /></label><label>Relationship owner<input name="owner" required maxLength={160} placeholder="Human owner" /></label><button className="button primary" disabled={busy}>Create contact</button></form><form className="panel form" onSubmit={(event) => submit(event, 'draft_agent_task')}><div className="panel-head"><div><h2>Draft agent work</h2><p>Creates a non-executing draft. Human approval is still required.</p></div></div><label>Contact<select name="contactId" defaultValue=""><option value="">No specific contact</option>{contacts.map((contact) => <option value={contact.id} key={contact.id}>{contact.name}</option>)}</select></label><label>CRM agent<select name="agentId" defaultValue="BSTA-CRM-001"><option value="BSTA-CRM-001">CRM Research Analyst</option><option value="BSTA-CRM-002">CRM Follow-up Planner</option></select></label><label>Task type<input name="taskType" required maxLength={100} placeholder="Research brief" /></label><label>Internal instruction<textarea name="instruction" required maxLength={4000} rows={4} placeholder="Draft an internal summary; do not contact anyone." /></label><button className="button secondary" disabled={busy}>Save draft task</button></form>{message ? <p className="notice">{message}</p> : null}</section>;
}
