'use client';
import {useMemo,useState} from 'react';
type Project={id:string;name:string;productionUrl:string|null};
type RecordItem=Record<string,unknown>;
type Draft={contract:RecordItem;workflow:RecordItem;risk:'low'|'medium'|'high'};
async function api(path:string,init:RequestInit){const response=await fetch(path,{...init,headers:{'content-type':'application/json',...init.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;}
export function WorkflowFactoryConsole({projects,initialWorkflows,initialExecutions,configured}:{projects:Project[];initialWorkflows:RecordItem[];initialExecutions:RecordItem[];configured:boolean}){
 const [projectId,setProjectId]=useState(projects[0]?.id||''),[intent,setIntent]=useState(''),[risk,setRisk]=useState<'low'|'medium'|'high'>('medium');
 const [recommendations,setRecommendations]=useState<RecordItem[]>([]),[draft,setDraft]=useState<Draft|null>(null),[contractText,setContractText]=useState(''),[workflowText,setWorkflowText]=useState('');
 const [workflows,setWorkflows]=useState(initialWorkflows),[executions,setExecutions]=useState(initialExecutions),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState('');
 const project=projects.find(item=>item.id===projectId),selectedWorkflow=useMemo(()=>workflows.find(item=>String(item.id)===selected),[workflows,selected]);
 const run=async(work:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await work();}catch(error){setMessage(error instanceof Error?error.message:'Request failed');}finally{setBusy(false);}};
 const factory=(action:string,extra:RecordItem={})=>api('/api/workflows/factory',{method:'POST',body:JSON.stringify({action,projectId,...extra})});
 const refresh=async()=>{const data=await api('/api/workflows',{method:'GET'});setWorkflows(data.workflows||[]);setExecutions(data.executions||[]);};
 const makeDraft=async(text=intent,chosenRisk=risk)=>{const data=await factory('draft',{intent:text,risk:chosenRisk}) as Draft;setDraft(data);setContractText(JSON.stringify(data.contract,null,2));setWorkflowText(JSON.stringify(data.workflow,null,2));setMessage('Draft created. Review and run the safe test.');};
 const parsed=()=>({contract:JSON.parse(contractText),workflow:JSON.parse(workflowText)});
 return <div className="page-stack">
  {!configured?<section className="notice error">Workflow deployment is locked until N8N_API_KEY is configured.</section>:null}
  <section className="panel form"><div className="panel-head"><div><h2>1–3. Choose a project and describe the automation</h2><p>Agent Foundry can recommend opportunities or draft from your own request.</p></div></div>
   <label>Authorized project<select value={projectId} onChange={event=>{setProjectId(event.target.value);setDraft(null);setRecommendations([]);}}>{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
   <label>What should the workflow accomplish?<textarea rows={4} value={intent} onChange={event=>setIntent(event.target.value)} placeholder="Example: Check production health every 10 minutes and notify me after two failures."/></label>
   <label>Risk<select value={risk} onChange={event=>setRisk(event.target.value as typeof risk)}><option value="low">Low — internal/read-only</option><option value="medium">Medium — external notification or write</option><option value="high">High — money, deletion, production, or public action</option></select></label>
   <div className="form-actions"><button className="button secondary" disabled={busy||!projectId} onClick={()=>run(async()=>{const data=await factory('recommend');setRecommendations(data.recommendations||[]);setMessage('Recommendations generated from current project state.');})}>Recommend workflows</button><button className="button primary" disabled={busy||!projectId||intent.trim().length<12} onClick={()=>run(()=>makeDraft())}>Generate draft</button></div>
   {recommendations.length?<div className="list">{recommendations.map(item=><button className="approval-row workflow-recommendation" key={String(item.id)} onClick={()=>{const text=String(item.description);setIntent(text);setRisk(item.risk as typeof risk);void run(()=>makeDraft(text,item.risk as typeof risk));}}><div><h3>{String(item.title)}</h3><p>{String(item.description)} · {String(item.value)}</p></div><span>Use →</span></button>)}</div>:null}
  </section>
  {draft?<section className="panel form"><div className="panel-head"><div><h2>4–6. Review, test, and deploy disabled</h2><p>Edit the contract or n8n JSON. Credentials must be n8n references—never secret values.</p></div></div>
   <label>Workflow Contract<textarea className="code-editor" rows={18} value={contractText} onChange={event=>setContractText(event.target.value)}/></label>
   <label>n8n workflow JSON<textarea className="code-editor" rows={18} value={workflowText} onChange={event=>setWorkflowText(event.target.value)}/></label>
   <div className="form-actions"><button className="button secondary" disabled={busy} onClick={()=>run(async()=>{const data=await factory('validate',parsed());setMessage(data.valid?'Safe dry-run passed: schema, scope, node allowlist, connections, and secret checks passed. No external action executed.':'Validation failed: '+[...(data.contractErrors||[]),...(data.workflowErrors||[])].join('; '));})}>Run safe test</button><button className="button primary" disabled={busy||!configured} onClick={()=>run(async()=>{const data=parsed();await api('/api/workflows',{method:'POST',body:JSON.stringify({projectId,contract:data.contract,workflow:data.workflow,risk})});await refresh();setMessage('Deployed to n8n in disabled state. Review it below before activation.');})}>Deploy disabled</button></div>
  </section>:null}
  <section className="panel"><div className="panel-head"><div><h2>7–9. Approve, monitor, revise, pause, or retire</h2><p>{workflows.length} managed workflow{workflows.length===1?'':'s'} · {executions.length} recent execution{executions.length===1?'':'s'}</p></div><button className="button secondary" disabled={busy} onClick={()=>run(refresh)}>Refresh</button></div>
   {workflows.length?<div className="list">{workflows.map(item=><div className="list-row" key={String(item.id)}><span><strong>{String(item.name||item.id)}</strong><small>{item.active?'Active':'Disabled'} · ID {String(item.id)}</small></span><div className="action-buttons"><button className="button secondary" onClick={()=>{setSelected(String(item.id));setWorkflowText(JSON.stringify({name:item.name,nodes:item.nodes,connections:item.connections,settings:item.settings||{}},null,2));setMessage('Workflow loaded for revision.');}}>Revise</button>{item.active?<button className="button secondary" disabled={busy} onClick={()=>run(async()=>{await api('/api/workflows/'+item.id,{method:'PATCH',body:JSON.stringify({action:'deactivate'})});await refresh();setMessage('Workflow paused.');})}>Pause</button>:<button className="button primary" disabled={busy} onClick={()=>run(async()=>{if(!confirm('Approve and activate this workflow? It may perform external actions.'))return;await api('/api/workflows/'+item.id,{method:'PATCH',body:JSON.stringify({action:'activate',approved:true})});await refresh();setMessage('Workflow approved and activated.');})}>Approve & activate</button>}<button className="button danger" disabled={busy} onClick={()=>run(async()=>{if(!confirm('Archive this workflow? It will be deactivated and removed from n8n.'))return;await api('/api/workflows/'+item.id+'/manage',{method:'DELETE',body:JSON.stringify({approved:true})});await refresh();setMessage('Workflow archived.');})}>Archive</button></div></div>)}</div>:<div className="empty">No workflows yet. Generate and safely deploy the first one above.</div>}
   {selectedWorkflow&&selected?<div className="form workflow-revision"><label>Revision JSON<textarea className="code-editor" rows={16} value={workflowText} onChange={event=>setWorkflowText(event.target.value)}/></label><div className="form-actions"><button className="button primary" disabled={busy} onClick={()=>run(async()=>{await api('/api/workflows/'+selected+'/manage',{method:'PUT',body:JSON.stringify({workflow:JSON.parse(workflowText)})});await refresh();setSelected('');setMessage('Workflow revision saved.');})}>Validate & save revision</button></div></div>:null}
   {executions.length?<div className="table-panel"><div className="table workflow-table"><div className="table-row table-head"><span>Execution</span><span>Workflow</span><span>Status</span><span>Started</span></div>{executions.slice(0,20).map(item=><div className="table-row" key={String(item.id)}><span>{String(item.id)}</span><span>{String(item.workflowId||'Unknown')}</span><span className={'badge '+(item.status==='success'?'status-approved':'status-failed')}>{String(item.status||'Unknown')}</span><span>{item.startedAt?new Date(String(item.startedAt)).toLocaleString():'Unknown'}</span></div>)}</div></div>:null}
  </section>
  {message?<div className={message.toLowerCase().includes('fail')?'notice error':'notice workflow-message'}>{message}</div>:null}
 </div>;
}
