'use client';

import { useEffect, useState } from 'react';

type Project = { id:string; name:string; githubOwner:string; githubRepo:string; defaultBranch:string; authorisedStatus:boolean; spendingLimit:number; projectType:string; productionUrl:string|null; vercelProjectRef:string|null; _count:{tasks:number} };
const labels:Record<string,string>={web_app:'Web app',website:'Website',mobile_app:'Mobile app',api:'API / service',automation:'Automation',library:'Library',company_discovery:'Company intelligence',other:'Other'};

export default function Workspaces(){
 const[projects,setProjects]=useState<Project[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const response=await fetch('/api/projects'),data=await response.json();if(response.ok)setProjects(data);else setMessage(data.error||'Unable to load Boosta workspaces');};
 useEffect(()=>{void load();},[]);
 async function update(body:unknown){setBusy(true);setMessage('');try{const response=await fetch('/api/projects',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok){setMessage(data.error||`Request failed (${response.status})`);return null}await load();return data}catch(error){setMessage(error instanceof Error?error.message:'Unable to reach Boosta OS');return null}finally{setBusy(false)}}
 async function authorize(project:Project){const data=await update({id:project.id,action:project.authorisedStatus?'deauthorize':'authorize'});if(data)setMessage(`${project.name} ${data.authorisedStatus?'authorized':'deauthorized'}.`)}
 async function editLink(project:Project){const value=window.prompt('Public HTTPS address for this Boosta workspace (leave blank if it is not deployed):',project.productionUrl||'');if(value===null)return;const data=await update({id:project.id,action:'update_public_link',productionUrl:value,projectType:project.projectType});if(data)setMessage(`${project.name} public link updated.`)}
 async function aiManager(project:Project){const brief=window.prompt(`Describe the complete outcome, target users, business goals, features, budget, deadline, marketing, operations, and definition of success for ${project.name}:`);if(brief===null)return;if(brief.trim().length<80){setMessage('Provide at least 80 characters so the AI manager has enough workspace detail.');return}setBusy(true);setMessage('Creating AI manager evaluation…');try{const created=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:project.id,title:`AI Project Manager Evaluation — ${project.name}`,completeInstruction:`Act as the AI Project Manager for this Boosta Förlag workspace. Evaluate the business, product, users, market research, branding, marketing, content, operations, inventory or suppliers when relevant, technical architecture, security, legal/privacy risks, deployment, analytics, budget, timeline, and success measures. Select the complete specialist team needed from the verified agent catalog. Produce a phased master plan with dependencies, deliverables, risks, acceptance criteria, and explicit owner approval gates. Do not execute, spend money, publish, contact third parties, or merge code. Workspace brief:\n\n${brief.trim()}`,riskLevel:'high'})});const task=await created.json();if(!created.ok)throw new Error(task.error||'Unable to create evaluation');const queued=await fetch(`/api/tasks/${task.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'request_plan'})}),result=await queued.json();if(!queued.ok)throw new Error(result.error||'Unable to start evaluation');window.location.href=`/tasks/${task.id}`;}catch(error){setMessage(error instanceof Error?error.message:'AI manager evaluation failed');setBusy(false)}}
 return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">BOOSTA FÖRLAG</p><h1>Workspaces</h1><p>Technical workspaces used by Boosta OS to govern company missions, repositories, automation, and spending.</p></div></header><div className="notice">Boosta OS is dedicated to Boosta Förlag. Workspaces are created only by approved company workflows, not added manually from the dashboard.</div>{message&&<div className="notice">{message}</div>}<section className="page-stack">{projects.map(project=><article className="panel project-card" key={project.id}><div className="panel-head"><div><span className="eyebrow">{labels[project.projectType]||project.projectType}</span><h2>{project.name}</h2><p>{project.githubOwner}/{project.githubRepo} · {project.defaultBranch}</p></div><span className={`badge ${project.authorisedStatus?'status-approved':'status-awaiting_plan_approval'}`}>{project.authorisedStatus?'Authorised':'Not authorised'}</span></div>{project.productionUrl?<a className="project-url" href={project.productionUrl} target="_blank" rel="noreferrer">↗ {project.productionUrl}</a>:<button className="project-url missing" onClick={()=>editLink(project)}>+ Assign public domain or web link</button>}<div className="project-meta"><span>{project._count.tasks} tasks</span><span>${project.spendingLimit} limit</span><span>{project.vercelProjectRef?'Vercel connected':'Deployment not connected'}</span></div><div className="action-buttons"><button disabled={busy} onClick={()=>aiManager(project)} className="button secondary">AI Manager</button><button disabled={busy} onClick={()=>authorize(project)} className="button primary">{project.authorisedStatus?'Deauthorize':'Authorize'}</button><button disabled={busy} onClick={()=>editLink(project)} className="button secondary">Edit public link</button></div></article>)}{!projects.length&&<div className="empty panel">No Boosta workspaces are configured yet. An approved company workflow will create the first one.</div>}</section></div>;
}
