import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { getSession } from '@/lib/auth';
import prisma from '@/lib/prisma';
import TaskActions from '@/components/task-actions';

export const dynamic = 'force-dynamic';

type Plan = {
  summary?: string;
  selectedAgents?: Array<{ catalogId?: string; name?: string; reason?: string; responsibilities?: string[] }>;
  catalogSource?: { repository?: string; commit?: string };
  steps?: Array<{ order?: number; title?: string; description?: string; files?: string[]; validation?: string }>;
  risks?: string[];
  acceptanceCriteria?: string[];
};

export default async function TaskDetail({ params }: { params: Promise<{ id: string }> }) {
  const session = await getSession();
  if (!session) redirect('/login');

  const { id } = await params;
  const task = await prisma.task.findUnique({
    where: { id },
    include: {
      project: true,
      agentRuns: { orderBy: { createdAt: 'desc' } },
      approvals: { orderBy: { requestedAt: 'desc' } },
    },
  });
  if (!task) notFound();

  const planner = task.agentRuns.find((run) => run.role === 'planner' && run.status === 'success' && run.outputSummary);
  let plan: Plan | null = null;
  try {
    plan = planner?.outputSummary ? JSON.parse(planner.outputSummary) : null;
  } catch {}

  return <div className="page-stack">
    <header className="page-header">
      <div>
        <Link className="back" href="/tasks">← Tasks</Link>
        <h1>{task.title}</h1>
        <p>{task.project.name} · {task.project.githubOwner}/{task.project.githubRepo}</p>
      </div>
      <span className={`badge large status-${task.status}`}>{task.status.replaceAll('_', ' ')}</span>
    </header>

    <TaskActions taskId={task.id} status={task.status} state={task.state}/>

    <section className="grid-two detail-grid">
      <div className="page-stack">
        <div className="panel">
          <div className="panel-head"><h2>Instruction</h2><span className={`risk risk-${task.riskLevel}`}>{task.riskLevel} risk</span></div>
          <p className="instruction">{task.completeInstruction}</p>
        </div>

        {plan && <div className="panel plan">
          <div className="panel-head">
            <div><h2>Proposed implementation plan</h2><p>Generated by the configured planner · requires human approval</p></div>
            <span className="badge status-awaiting_plan_approval">Read only</span>
          </div>
          <p className="plan-summary">{plan.summary}</p>
          {plan.selectedAgents?.length ? <div className="plan-box success">
            <strong>Selected agent team</strong>
            <ul>{plan.selectedAgents.map((agent, index) => <li key={`${agent.catalogId}-${index}`}>
              <a href={`https://github.com/cjram71/500-AI-Agents-Projects/tree/${plan.catalogSource?.commit || ''}/agents/${agent.catalogId}`} target="_blank" rel="noreferrer"><strong>{agent.name || agent.catalogId}</strong></a>
              <p>{agent.reason}</p>
              {agent.responsibilities?.length ? <small>Responsibilities: {agent.responsibilities.join(' · ')}</small> : null}
            </li>)}</ul>
            {plan.catalogSource?.commit ? <small>Catalog: cjram71/500-AI-Agents-Projects · {plan.catalogSource.commit.slice(0, 12)}</small> : null}
          </div> : null}
          <ol>{plan.steps?.map((step, index) => <li key={`${step.order}-${index}`}>
            <strong>{step.title}</strong><p>{step.description}</p>
            {step.files?.length ? <small>Files: {step.files.join(', ')}</small> : null}
            <small>Validation: {step.validation}</small>
          </li>)}</ol>
          {plan.risks?.length ? <div className="plan-box"><strong>Risks</strong><ul>{plan.risks.map((risk, index) => <li key={index}>{risk}</li>)}</ul></div> : null}
          {plan.acceptanceCriteria?.length ? <div className="plan-box success"><strong>Acceptance criteria</strong><ul>{plan.acceptanceCriteria.map((criterion, index) => <li key={index}>{criterion}</li>)}</ul></div> : null}
        </div>}

        {planner?.outputSummary && <details className="panel"><summary>Raw manager result</summary><pre className="code-block">{planner.outputSummary}</pre></details>}

        <div className="panel">
          <div className="panel-head"><h2>Agent runs</h2><span>{task.agentRuns.length}</span></div>
          {task.agentRuns.map((run) => <div className="timeline-row" key={run.id}><span className="timeline-dot"/><div>
            <strong>{run.role} · {run.model}</strong>
            <small>{run.status} · {run.tokenUsage.toLocaleString()} tokens · {new Date(run.createdAt).toLocaleString()}</small>
            {run.outputSummary && run.role !== 'planner' && <p>{run.outputSummary}</p>}
            {run.errorInfo && <p className="error-text">{run.errorInfo}</p>}
          </div></div>)}
          {!task.agentRuns.length && <div className="empty">No agent has run this task yet.</div>}
        </div>
      </div>

      <aside className="page-stack">
        <div className="panel facts">
          <h2>Task details</h2>
          <dl>
            <dt>Status</dt><dd>{task.status.replaceAll('_', ' ')}</dd>
            <dt>Agent</dt><dd>{task.assignedAgent || 'Not assigned'}</dd>
            <dt>Branch</dt><dd>{task.branchName || 'Not created'}</dd>
            <dt>Tokens</dt><dd>{task.tokenUsage.toLocaleString()}</dd>
            <dt>Estimated cost</dt><dd>${task.estimatedCost.toFixed(2)}</dd>
            <dt>Created</dt><dd>{new Date(task.createdAt).toLocaleString()}</dd>
          </dl>
          {task.pullRequestUrl && <a className="button secondary" href={task.pullRequestUrl}>Open pull request</a>}
          {task.previewUrl && <a className="button secondary" href={task.previewUrl}>Open preview</a>}
        </div>

        <div className="panel">
          <div className="panel-head"><h2>Approvals</h2><span>{task.approvals.length}</span></div>
          {task.approvals.map((approval) => <div className="approval-mini" key={approval.id}>
            <strong>{approval.approvalType}</strong>
            <span className={`badge decision-${approval.decision}`}>{approval.decision}</span>
            <small>{new Date(approval.requestedAt).toLocaleString()}</small>
          </div>)}
          {!task.approvals.length && <div className="empty">No approval requests.</div>}
        </div>
      </aside>
    </section>
  </div>;
}
